// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTGowf-YKT1YYJs6fTyaSnVHBaAWh0Xrc',
    appId: '1:955828925161:web:a12e8fde7f4902ab1bf678',
    messagingSenderId: '955828925161',
    projectId: 'creativa-flutter-sanad',
    authDomain: 'creativa-flutter-sanad.firebaseapp.com',
    storageBucket: 'creativa-flutter-sanad.appspot.com',
    measurementId: 'G-NGQ861GQ8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlmsdm_M7ClGuOSJuLml4Ag_xFK3KRqKs',
    appId: '1:955828925161:android:80e19acf91009d7f1bf678',
    messagingSenderId: '955828925161',
    projectId: 'creativa-flutter-sanad',
    storageBucket: 'creativa-flutter-sanad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa8wcjXPGtMtrQ77Le5mGVMUlbFNwIV78',
    appId: '1:955828925161:ios:a211f2d87365f5b21bf678',
    messagingSenderId: '955828925161',
    projectId: 'creativa-flutter-sanad',
    storageBucket: 'creativa-flutter-sanad.appspot.com',
    iosBundleId: 'com.example.creativePortsaid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa8wcjXPGtMtrQ77Le5mGVMUlbFNwIV78',
    appId: '1:955828925161:ios:a211f2d87365f5b21bf678',
    messagingSenderId: '955828925161',
    projectId: 'creativa-flutter-sanad',
    storageBucket: 'creativa-flutter-sanad.appspot.com',
    iosBundleId: 'com.example.creativePortsaid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTGowf-YKT1YYJs6fTyaSnVHBaAWh0Xrc',
    appId: '1:955828925161:web:253a301f49f858ef1bf678',
    messagingSenderId: '955828925161',
    projectId: 'creativa-flutter-sanad',
    authDomain: 'creativa-flutter-sanad.firebaseapp.com',
    storageBucket: 'creativa-flutter-sanad.appspot.com',
    measurementId: 'G-8WZW6Y2MXC',
  );
}
